/*
 * @Author: huanglin
 * @LastEditTime: 2024-07-16 23:54:40
 */
export const metadata = {
  title: 'next Demo测试',
  icon: './favicon.ico',
  description: 'Generated by create next app'
}

export default function BaseHead({ children }) {
  return (
    <>
      <title>{metadata.title}</title>
      <meta name='description' content={metadata.description} />
    </>
  )
}
